### ISSUE TITLE
[Bug] Dev branch last commit

### ISSUE THREAD

**Issue by konoashi** [BiscuitDevelopment/SkyblockAddons#499] opened 2021-01-30 16:51 UTC
After building, when launching this happening:
![image](https://user-images.githubusercontent.com/64316846/106362538-b5cc4380-6323-11eb-8d08-cb034916cc7d.png)
Other mods: Skyblock Extras 2.0.0

**Comment by 116s** [comment] 2021-01-30 23:40
Duplicate of #467.

**Comment by ILikePlayingGames** [comment] 2021-02-08 03:24
Closed as duplicate

**Closed by ILikePlayingGames** 2021-02-08 03:24 UTC
Labels: bug
