### ISSUE TITLE
[Bug] game crashed

### ISSUE THREAD

**Issue by WIFIGUN** [BiscuitDevelopment/SkyblockAddons#512] opened 2021-03-10 22:09 UTC
**Screenshots/Video**
[https://youtu.be/DDOE74NL29c](https://youtu.be/DDOE74NL29c)

**Crash Report**
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;
結束代碼：-1

[latest.log](https://github.com/BiscuitDevelopment/SkyblockAddons/files/6119089/latest.log)
[launcher_log.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/6119109/launcher_log.txt)
[launcher_cef_log.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/6119108/launcher_cef_log.txt)
[crash-2021-03-11_05.57.59-client.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/6119091/crash-2021-03-11_05.57.59-client.txt)

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.6.0-beta.7

**Comment by PumpkinXD** [comment] 2021-03-11 11:12
> **Screenshots/Video**
> https://youtu.be/DDOE74NL29c
> 
> **Crash Report**
> The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
> Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;
> 結束代碼：-1
> 
> [latest.log](https://github.com/BiscuitDevelopment/SkyblockAddons/files/6119089/latest.log)
> [launcher_log.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/6119109/launcher_log.txt)
> [launcher_cef_log.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/6119108/launcher_cef_log.txt)
> [crash-2021-03-11_05.57.59-client.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/6119091/crash-2021-03-11_05.57.59-client.txt)
> 
> **System Information**
> 
> * OS: Windows 10
> * Minecraft Version: 1.8.9
> * Forge Version: 11.15.1.2318
> * SkyblockAddons Version: 1.6.0-beta.7

Duplicate of #467 
Fix: #469

**Comment by ILikePlayingGames** [comment] 2021-03-12 07:37
Pumpkin is correct, closed as duplicate.

**Closed by ILikePlayingGames** 2021-03-12 07:37 UTC
Labels: bug
