### ISSUE TITLE
Slot locking doesn't work sometimes.

### ISSUE THREAD

**Issue by fantauvaxD** [BiscuitDevelopment/SkyblockAddons#147] opened 2019-10-06 00:23 UTC
Sometimes, after switching slots, you're able to drop items from a locked slot.
In order to replicate:
1. Disable hypixel's skyblock item drop confirmation
2. Keep switching between a locked and an unlocked slot while you spam the drop key
3. Drop your runaan's bow which is worth around 1.7mil
4. Cry on a corner

https://youtu.be/-H_qSEuIu0g (wasn't able to send the video without uploading it to youtube, sorry!)

**Comment by tomocrafter** [comment] 2019-10-11 22:00
This is not a bug. If the player sends a packet to drop the item to the server and the player also sends a packet to change the slot before the server actually drops the item, the server will try to "drop the item that it currently player has", Therefore the item in the locked slot will be dropped.

In order to solve this problem, it is necessary to prohibit the movement of the slot until the event change packet is sent from the server after dropping the item.

**Comment by Sunjaeeeee** [comment] 2019-11-23 22:32
> This is not a bug. If the player sends a packet to drop the item to the server and the player also sends a packet to change the slot before the server actually drops the item, the server will try to "drop the item that it currently player has", Therefore the item in the locked slot will be dropped.
> 
> In order to solve this problem, it is necessary to cancel the movement of the slot until the inventory change packet is sent from the server after dropping the item.

This is a bug because the mod is client side and not server side so before sending a packet to the server to drop the item, the client side should have been blocked it because it’s locked. This also does not happen without sba and I have been able to replicate this by pressing ‘2’ and ‘q’ at the same time while the locked slot and item is at 1

**Comment by biscuut** [comment] 2020-06-27 03:53
Should be fixed in 1.5.0, added a little cooldown on slot switch as a workaround

**Closed by biscuut** 2020-06-27 03:53 UTC
Labels: bug
