### ISSUE TITLE
[Bug] XP show thingy doesnt work after skill level 5

### ISSUE THREAD

**Issue by TerrificTable** [BiscuitDevelopment/SkyblockAddons#587] opened 2021-12-31 20:52 UTC
If i surpace level 5 in a skill the xp i gain after that doesnt show in the xp gained bar thingy

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. surpace level 5 in any skill
2. after that the gained xp in that skill will not be shown in the bar thingy
 
The gained xp should be displayed after skill level 5 but it doesnt

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.6.1

**Other Installed Mods**
- Dankers Skyblock Mod
- BazaarNotifyer
- NotEnoughUpdates
- Patcher
- s0lskyblock
- (Optifine)

**Comment by ILikePlayingGames** [comment] 2022-01-22 11:31
Duplicate of #559

**Closed by ILikePlayingGames** 2022-01-22 11:31 UTC
Labels: bug
