### ISSUE TITLE
Zealot Counter not increasing with ranged kills

### ISSUE THREAD

**Issue by kada49** [BiscuitDevelopment/SkyblockAddons#663] opened 2022-10-16 10:19 UTC
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
When killing a zealot with a ranged weapon (I am using a juju shortbow, same effect with livid dagger throw, right click Flower of Truth) the zealot counter does not increase, even though I still spawn special zealots by killing them by bow.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
Use a juju bow or any ranged weapon, shoot a zealot and kill it, the counter does not increase.

**Expected behavior**
Should add 1 kill to the counter per killed zealot

**System Information**
 - OS: Windows 11
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.7.0
**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Essential 10597
- Autotip 3.0
- Cowlection 0.14.0
- FPS-Display 1.1.2
- Hypixel Autocomplete Mod
- Patcher 1.8.5
- Scrollable Tooltips
- SkyblockExtras 2.2.0-Pre8

**Comment by SemGamerNL** [comment] 2022-10-20 11:12
its not only with bows its witch all range attacks
like my fot and livid dagger arnt counting ether with range

**Comment by Ghoslain** [comment] 2022-10-27 11:52
Any plans on adding the color & kill count and all zealots features to newest zone & zealot bruisers? :)

**Comment by ILikePlayingGames** [comment] 2022-10-30 04:56
Duplicate of #465

**Closed by ILikePlayingGames** 2022-10-30 04:56 UTC
Labels: bug
