### ISSUE TITLE
[Bug] java.lang.NoSuchMethodError (development branch)`

### ISSUE THREAD

**Issue by TheLegendOfKitty** [BiscuitDevelopment/SkyblockAddons#467] opened 2020-12-07 16:42 UTC
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Game crashes on start when attempting to load skyblockaddons.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Use the latest dev build rn
2. launch game
3. see error

**Expected behavior**
I want the game to launch

**Screenshots**
![image](https://user-images.githubusercontent.com/61601745/101378148-948d3080-3867-11eb-97f6-7f3d82a8fcfa.png)

**Crash Report**
https://gist.github.com/TheLegendOfKitty/e62f1cdc32b05e045e64ff5c7d41dfb9

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.6.0 Beta 7

**Other Installed Mods**
I can't be assed to show you any mods just take my zip file of them
https://digestedmosquito-staticassets.s3-us-west-2.amazonaws.com/mods.zip

**Comment by TrashCan69420** [comment] 2020-12-07 20:49
1 most of your mods are out of date or are not needed such as modcore container
and your neu is a month or two 

so try updating and deleting your useless mods and see if it still crashes

**Comment by Phoube** [comment] 2020-12-07 21:17
Dev build is definitely a WIP, so take that into account. Other than that, the log says it's an issue with one of the language files. Which sba language were you using during the crash?

**Comment by Levi-r** [comment] 2020-12-07 22:52
I also have this bug

**Comment by TheLegendOfKitty** [comment] 2020-12-08 01:57
> Dev build is definitely a WIP, so take that into account. Other than that, the log says it's an issue with one of the language files. Which sba language were you using during the crash?

English. Also I know it is a dev build, the whole point of reporting this bug is so that they can fix the dev build before they release?

**Comment by TrashCan69420** [comment] 2020-12-08 03:15
> 
> 
> > Dev build is definitely a WIP, so take that into account. Other than that, the log says it's an issue with one of the language files. Which sba language were you using during the crash?
> 
> English. Also I know it is a dev build, the whole point of reporting this bug is so that they can fix the dev build before they release?

the dev branch is also behind the actual beta version as it is in a private repo

**Comment by NeoNC72** [comment] 2020-12-08 14:34
> 1 most of your mods are out of date or are not needed such as modcore container
> and your neu is a month or two
> 
> so try updating and deleting your useless mods and see if it still crashes

deff not issue with other mods, still crashes even wothout any other mods

**Comment by RefusingsPaPa** [comment] 2020-12-12 19:14
Minecraft 1.8.9 uses GSON 2.2.4, to use the methods that Biscuit uses you need something like GSON 2.8.6, which because Java is annoying, the one that Minecraft is using overrules the one that Biscuit might want to put in the .jar.  The only reason this got past Biscuit is that if you run Minecraft through the gradle run system, it doesn't use the GSON library that Minecraft uses, it uses the one that Biscuit uses...  Which wasn't annoying to find out at all...

Simply revert the change that is currently on [this](https://github.com/BiscuitDevelopment/SkyblockAddons/blob/e5a928aab4dcf6fd5a0dbb6929d6254d4e529802/src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java#L662) line back to what it was/is on the main build [this](https://github.com/BiscuitDevelopment/SkyblockAddons/blob/c3d6b11fe147f2d92a69af279db203cd25083599/src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java#L781).

**Comment by Phoube** [comment] 2020-12-12 19:39
Or follow #469 for an alternative fix

**Comment by RefusingsPaPa** [comment] 2020-12-12 21:20
> Or follow #469 for an alternative fix
It's the same fix with 1 extra step...

**Comment by biscuut** [comment] 2020-12-12 22:22
Yep this was already fixed locally, will push it when I finish up some other changes I was doing, but somehow a gson dependency slipped in from one of dependencies and it got used. I didn't catch it because it runs completely fine in a development environment xD

**Comment by ILikePlayingGames** [comment] 2020-12-13 08:11
Oh yeah, I changed that line because the method was showing as deprecated. I did not realize it was using the wrong Gson version.

**Comment by G4CE-Neiz** [comment] 2021-06-19 07:22
It's a problem within Utils.java in the loadLanguageFile. I found a solution to avoid this crash simply just revert one of the lines to the previous version. thankfully i have one of the previous version

this is the problem:
Caused by: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;
	at codes.biscuit.skyblockaddons.utils.Utils.loadLanguageFile(Utils.java:662)

I grab that from the crash report

the solution is just to replace the line 662 on Utils.java
from:
                main.getConfigValues().setLanguageConfig(JsonParser.parseString(dataString).getAsJsonObject());
to:
                main.getConfigValues().setLanguageConfig(new JsonParser().parse(dataString).getAsJsonObject());

it works wonders for me

**Comment by ILikePlayingGames** [comment] 2021-07-10 03:24
This has now been fixed with the release of v1.6.0.

**Closed by ILikePlayingGames** 2021-07-10 03:24 UTC
Labels: bug
